export { environ_get } from "./environ_get.js"
export { environ_sizes_get } from "./environ_sizes_get.js"
export { fd_close } from "./fd_close.js"
export { fd_read } from "./fd_read.js"
export { fd_seek } from "./fd_seek.js"
export { fd_write } from "./fd_write.js"
export { proc_exit } from "./proc_exit.js"
